apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: "redis:{{- .Values.version }}"
          command: ["redis-server", "--requirepass", "testtest123", "--slaveof", "{{ .Values.name }}-redis", "6379"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-conf
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-redis-replica
spec:
  selector:
    app: redis
    role: replica
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
