apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.scaling.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.general.image }}:{{ .Values.general.version }}"
          
          {{- if .Values.networking.expose }}
          ports:
            - name: http
              containerPort: {{ .Values.networking.port }}
              protocol: TCP
          {{- end }}
          
          env:
          {{- if .Values.general.environment }}
          {{- toYaml .Values.general.environment | indent 12 }}
          {{- end }}

          resources:
            {{- if .Values.scaling.resources.memory }}
            limits:
              memory: "{{ .Values.scaling.resources.memory }}Gi"
            {{- end }}
            {{- if .Values.scaling.resources.cpu }}
            requests:
              cpu: "{{ .Values.scaling.resources.cpu }}"
            {{- end }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
