apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ (.Values.scaling).replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.general.image }}:{{ .Values.general.version }}"
          {{- if ((.Values.networking).expose) }}
          ports:
            - name: http
              containerPort: {{ .Values.networking.port | default 80 }}
              protocol: TCP
          {{- end }}
          env:
          {{- if ((.Values.general).environment) }}
          {{- range $key, $value := (.Values.general).environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if or ((.Values.scaling).resources).memory ((.Values.scaling).resources).cpu }}
          resources:
            {{- if ((.Values.scaling).resources).memory }}
            limits:
              memory: {{ ((.Values.scaling).resources).memory }}Gi
            {{- end }}
            {{- if or ((.Values.scaling).resources).memory ((.Values.scaling).resources).cpu }}
            requests:
              {{- if ((.Values.scaling).resources).cpu }}
              cpu: {{ ((.Values.scaling).resources).cpu }}
              {{- end }}
              {{- if ((.Values.scaling).resources).memory }}
              memory: {{ ((.Values.scaling).resources).memory }}Gi
              {{- end }}
            {{- end }}
          {{- end }}
